create extension if not exists pgcrypto;
create type public.user_role as enum ('client','seller','admin');
create type public.sale_kind as enum ('in_person','delivery');
create type public.payment_method as enum ('cash','pix','card','courtesy','loyalty');

create table public.profiles (id uuid primary key references auth.users on delete cascade, name text not null, phone text, role user_role not null default 'client', referral_code text unique not null default upper(substr(encode(gen_random_bytes(6),'hex'),1,10)), referred_by uuid references public.profiles, created_at timestamptz not null default now());
create table public.families (id uuid primary key default gen_random_uuid(), name text not null, invite_code text unique not null default upper(substr(encode(gen_random_bytes(6),'hex'),1,10)), owner_id uuid not null references public.profiles, created_at timestamptz not null default now());
create table public.family_members (family_id uuid references public.families on delete cascade, profile_id uuid references public.profiles on delete cascade, joined_at timestamptz not null default now(), primary key(family_id,profile_id), unique(profile_id));
create table public.cash_sessions (id uuid primary key default gen_random_uuid(), business_date date unique not null default current_date, opened_by uuid not null references public.profiles, opened_at timestamptz not null default now(), closed_at timestamptz, opening_fund numeric(12,2) not null check(opening_fund>=0), available_slices integer not null check(available_slices>=0), closing_cash numeric(12,2), notes text);
create table public.sales (id uuid primary key default gen_random_uuid(), cash_session_id uuid not null references public.cash_sessions, seller_id uuid not null references public.profiles, quantity integer not null check(quantity>0), unit_price numeric(12,2) not null check(unit_price>=0), total numeric(12,2) generated always as (quantity*unit_price) stored, payment payment_method not null, kind sale_kind not null, created_at timestamptz not null default now());
create table public.sale_tokens (id uuid primary key default gen_random_uuid(), sale_id uuid unique not null references public.sales on delete cascade, token_hash text unique not null, expires_at timestamptz not null default now()+interval '7 days', claimed_by uuid references public.profiles, claimed_at timestamptz, created_at timestamptz not null default now());
create table public.loyalty_cards (id uuid primary key default gen_random_uuid(), profile_id uuid unique references public.profiles on delete cascade, family_id uuid unique references public.families on delete cascade, stamps integer not null default 0 check(stamps>=0), check((profile_id is null)<>(family_id is null)));
create table public.loyalty_events (id uuid primary key default gen_random_uuid(), card_id uuid not null references public.loyalty_cards, profile_id uuid references public.profiles, sale_id uuid references public.sales, event_type text not null check(event_type in ('purchase','referral','redeem','adjustment')), stamps integer not null, note text, created_at timestamptz not null default now());
create table public.rewards (id uuid primary key default gen_random_uuid(), card_id uuid not null references public.loyalty_cards, status text not null default 'available' check(status in ('available','redeemed','expired')), issued_at timestamptz not null default now(), redeemed_at timestamptz, sale_id uuid references public.sales);
create table public.referrals (id uuid primary key default gen_random_uuid(), referrer_id uuid not null references public.profiles, referred_id uuid unique not null references public.profiles, first_sale_id uuid unique references public.sales, bonus_event_id uuid unique references public.loyalty_events, status text not null default 'pending' check(status in ('pending','rewarded','cancelled')), created_at timestamptz not null default now());
create table public.app_settings (id boolean primary key default true check(id), store_name text not null default 'Adoce Brigaderia', slice_price numeric(12,2) not null default 16, average_cost numeric(12,2) not null default 6.67, stamps_required integer not null default 14, instagram_url text, whatsapp text, updated_at timestamptz not null default now());
create table public.weekly_flavors (id uuid primary key default gen_random_uuid(), name text not null, image_url text, active boolean not null default true, starts_on date, ends_on date);
create table public.audit_logs (id bigint generated always as identity primary key, actor_id uuid references public.profiles, action text not null, entity_type text not null, entity_id text, payload jsonb not null default '{}', created_at timestamptz not null default now());
create index sales_created_at_idx on public.sales(created_at desc);create index loyalty_events_card_idx on public.loyalty_events(card_id,created_at desc);
