import { expect, test, type Page } from '@playwright/test';

async function mockBetaApi(page:Page){
  await page.route('**/.netlify/functions/customer-register',async route=>{
    const body=route.request().postDataJSON();
    await route.fulfill({json:{token:'test-token',customer:{id:'c1',name:body.name,whatsapp:body.whatsapp,email:body.email||'',instagram:body.instagram||'',birth_date:body.birthDate||'',accepts_promotions:body.acceptsPromotions!==false},card:{stamps:0,stamps_required:14},events:[]}});
  });
  await page.route('**/.netlify/functions/customer-login',async route=>{
    const body=route.request().postDataJSON();
    await route.fulfill({json:{token:'test-token',customer:{id:'c1',name:'Cliente Beta',whatsapp:body.whatsapp,email:'',instagram:'',birth_date:'',accepts_promotions:true},card:{stamps:0,stamps_required:14},events:[]}});
  });
  await page.route('**/.netlify/functions/customer-update',async route=>{
    const body=route.request().postDataJSON();
    await route.fulfill({json:{customer:{id:'c1',name:body.name,whatsapp:body.whatsapp,email:body.email||'',instagram:body.instagram||'',birth_date:body.birthDate||'',accepts_promotions:body.acceptsPromotions!==false},card:{stamps:0,stamps_required:14},events:[]}});
  });
  await page.route('**/.netlify/functions/staff-login',async route=>{
    const body=route.request().postDataJSON();
    await route.fulfill({json:{token:'staff-token',operatorId:body.userId}});
  });
  await page.route('**/.netlify/functions/sale-create',async route=>{
    expect(route.request().headers().authorization).toBe('Bearer staff-token');
    await route.fulfill({json:{id:'sale-cloud',token:`ADOCE-TEST-${Date.now()}`}});
  });
  await page.route('**/.netlify/functions/loyalty-claim',async route=>{
    await route.fulfill({json:{customer:{id:'c1',name:'Cliente Beta',whatsapp:'85999990000',email:'',instagram:'',birth_date:'',accepts_promotions:true},card:{stamps:3,stamps_required:14},events:[{event_type:'purchase',stamps:3,note:'Compra registrada',created_at:new Date().toISOString()}]}});
  });
  await page.route('**/.netlify/functions/loyalty-adjust',async route=>{
    const body=route.request().postDataJSON();
    expect(route.request().headers().authorization).toBe('Bearer staff-token');
    await route.fulfill({json:{customer:{name:'Cliente Beta',whatsapp:body.whatsapp},card:{stamps:body.mode==='set'?body.stamps:body.stamps,stamps_required:14}}});
  });
}

async function reset(page:Page){await page.goto('/cadastro');await page.evaluate(()=>localStorage.clear());await page.reload()}
async function registerCustomer(page:Page){await page.goto('/cadastro');await page.getByRole('textbox',{name:'Nome'}).fill('Cliente Beta');await page.getByRole('textbox',{name:'WhatsApp'}).fill('85999990000');await page.getByLabel('Crie sua senha').fill('1234');await page.getByRole('checkbox',{name:/Aceito participar/}).check();await page.getByRole('checkbox',{name:/versão beta/}).check();await page.getByRole('button',{name:'Criar meu Adoce Club'}).click();await expect(page).toHaveURL(/\/cliente$/)}
async function loginAdmin(page:Page){await page.goto('/equipe');await page.getByLabel('PIN temporário').fill('1706');await page.getByRole('button',{name:'Entrar na operação'}).click();await expect(page).toHaveURL(/\/admin$/)}
async function openCash(page:Page){await loginAdmin(page);await page.goto('/admin/caixa');await page.getByRole('button',{name:/Abrir caixa agora|Atualizar caixa/}).click()}
async function choosePayment(page:Page,name:string){await page.getByRole('button',{name,exact:true}).click()}

test.beforeEach(async({page})=>{await mockBetaApi(page);await reset(page);await registerCustomer(page)});

test('cadastro beta exige dados, LGPD e cria acesso do cliente',async({page})=>{await reset(page);await page.getByRole('button',{name:'Criar meu Adoce Club'}).click();await expect(page.getByText('Informe nome, WhatsApp válido')).toBeVisible();await registerCustomer(page);await page.goto('/entrar');await page.getByRole('textbox',{name:'WhatsApp'}).fill('85999990000');await page.getByLabel('Senha').fill('1234');await page.getByRole('button',{name:'Entrar'}).click();await expect(page.getByText('Hoje é dia de fatia!')).toBeVisible()});

test('cliente home, navegação e logo sem borda preta',async({page})=>{await page.goto('/cliente');await expect(page.getByText('Hoje é dia de fatia!')).toBeVisible();await expect(page.locator('.loyalty-card .stamp-slot')).toHaveCount(14);await expect(page.locator('.brand-logo-frame')).toBeVisible();await expect(page.getByRole('link',{name:'Reservar agora'})).toBeVisible();await expect(page.locator('.promo-card-grid').getByText('Quinta-feira, 18/06',{exact:true})).toBeVisible();await page.getByRole('link',{name:'Mais'}).click();await expect(page.getByText('Meu Perfil')).toBeVisible()});

test('botões principais cabem no viewport mobile',async({page})=>{await page.goto('/cliente');const overflow=await page.locator('body').evaluate(el=>el.scrollWidth>el.clientWidth);expect(overflow).toBeFalsy();for(const button of await page.locator('.primary-button').all()){const box=await button.evaluate(el=>({scroll:el.scrollWidth,client:el.clientWidth,height:(el as HTMLElement).offsetHeight}));expect(box.scroll).toBeLessThanOrEqual(box.client+1);expect(box.height).toBeGreaterThanOrEqual(48)}});

test('configurações gerais, empresa e taxas persistem',async({page})=>{await loginAdmin(page);await page.goto('/admin/configuracoes');await page.getByLabel('Preço da fatia').fill('18');await page.getByLabel('Carimbos para prêmio').fill('12');await page.getByLabel('Instagram').fill('@adoceoficial');await page.getByLabel('WhatsApp').fill('85988887777');await page.getByRole('button',{name:'Salvar configurações'}).click();await page.reload();await expect(page.getByLabel('Preço da fatia')).toHaveValue('18');await expect(page.getByLabel('Carimbos para prêmio')).toHaveValue('12');await page.getByRole('button',{name:'Empresa',exact:true}).click();await page.getByLabel('Nome fantasia').fill('Adoce Festival');await expect(page.getByLabel('Latitude')).toHaveCount(0);await expect(page.getByLabel('Longitude')).toHaveCount(0);await page.getByRole('button',{name:'Salvar dados da empresa'}).click();await page.reload();await page.getByRole('button',{name:'Empresa',exact:true}).click();await expect(page.getByLabel('Nome fantasia')).toHaveValue('Adoce Festival')});

test('caixa cadastra sabores, caldas e venda usa esses dados',async({page})=>{await loginAdmin(page);await page.goto('/admin/caixa');await page.getByLabel('Sabor 1').fill('Morango Supremo');await page.getByLabel('Quantidade 1').fill('7');await page.getByLabel('Sabor 2').fill('Pistache');await page.getByLabel('Quantidade 2').fill('5');await page.getByLabel('Sabor 3').fill('');await page.getByLabel('Quantidade 3').fill('0');await page.getByLabel('Sabor 4').fill('');await page.getByLabel('Quantidade 4').fill('0');await page.getByLabel('Caldas disponíveis').fill('Ninho, Chocolate');await page.getByRole('button',{name:'Abrir caixa agora'}).click();await page.goto('/admin/vendas');await page.getByLabel('Sabor da fatia').selectOption('Pistache');await page.getByLabel('Calda disponível').selectOption('Chocolate');await page.getByRole('button',{name:/Cliente Presencial/}).click();await expect(page.getByText('Pistache · Calda: Chocolate')).toBeVisible();await page.goto('/cliente');await expect(page.getByText('Pistache')).toBeVisible()});

for(const method of ['Dinheiro','Pix','Cartão'])test(`${method} gera QR e venda paga`,async({page})=>{await openCash(page);await page.goto('/admin/vendas');await choosePayment(page,method);await page.getByRole('button',{name:/Cliente Presencial/}).click();await expect(page.getByRole('heading',{name:'Venda registrada!'})).toBeVisible();await expect(page.locator('.qr-frame svg')).toBeVisible()});

for(const method of ['Cortesia','Permuta','Fidelidade'])test(`${method} registra saída sem QR`,async({page})=>{await openCash(page);await page.goto('/admin/vendas');await choosePayment(page,method);await page.getByLabel('Observação').fill('Operação demonstrativa');await page.getByRole('button',{name:/Cliente Presencial/}).click();await expect(page.getByRole('heading',{name:'Saída registrada!'})).toBeVisible();await expect(page.getByText('Esta operação não gera QR nem carimbo.')).toBeVisible();await expect(page.locator('.qr-frame')).toHaveCount(0)});

test('Mercado Pago Point usa terminal do login e só gera QR aprovado',async({page})=>{await openCash(page);await page.goto('/admin/vendas');await expect(page.getByText('Terminal:')).toContainText('Maquininha Rubens');await choosePayment(page,'Mercado Pago Point');await page.getByRole('button',{name:/Cliente Presencial/}).click();await expect(page.getByRole('heading',{name:'Aguardando pagamento'})).toBeVisible();await expect(page.locator('.qr-frame')).toHaveCount(0);await page.getByRole('button',{name:'Pagamento aprovado'}).click();await expect(page.getByRole('heading',{name:'Venda registrada!'})).toBeVisible()});

test('login Beth carrega terminal Beth',async({page})=>{await page.goto('/equipe');await page.getByRole('button',{name:'Beth'}).click();await page.getByLabel('PIN temporário').fill('1906');await page.getByRole('button',{name:'Entrar na operação'}).click();await expect(page).toHaveURL(/\/vendedor$/);await page.goto('/admin/caixa');await page.getByRole('button',{name:/Abrir caixa agora|Atualizar caixa/}).click();await page.goto('/vendedor/nova-venda');await expect(page.getByText('Terminal:')).toContainText('Maquininha Beth')});

test('Mercado Pago Link pendente não gera carimbo e pago libera QR',async({page})=>{await openCash(page);await page.goto('/admin/vendas');await choosePayment(page,'Mercado Pago Link');await page.getByRole('button',{name:/Delivery/}).click();await expect(page.getByText('Enquanto pendente, não gera QR nem carimbo.')).toBeVisible();await expect(page.locator('.qr-frame')).toHaveCount(0);await page.getByRole('button',{name:'Pagamento aprovado'}).click();await expect(page.getByRole('heading',{name:'Venda registrada!'})).toBeVisible()});

test('desconto no fechamento reduz total e aparece no relatório',async({page})=>{await openCash(page);await page.goto('/admin/vendas');await page.getByLabel('Desconto').selectOption('percent');await page.getByLabel('Valor do desconto').fill('10');await page.getByLabel('Motivo').selectOption('Promoção');await page.getByLabel('Observação do desconto').fill('Balão promocional');await expect(page.getByText('Desconto: -R$ 4,80')).toBeVisible();await expect(page.getByText('Total: R$ 43,20')).toBeVisible();await page.getByRole('button',{name:/Cliente Presencial/}).click();await expect(page.getByRole('heading',{name:'Venda registrada!'})).toBeVisible();await page.goto('/admin/relatorios');await expect(page.getByText('Descontos concedidos')).toBeVisible();await expect(page.getByText('R$ 4,80')).toBeVisible()});

test('gasto aparece no relatório e fechamento',async({page})=>{await openCash(page);await page.getByLabel('Valor').fill('25');await page.getByLabel('Descrição').fill('Lanche da equipe');await page.getByRole('button',{name:'Salvar gasto'}).click();await expect(page.getByText('Gasto registrado.')).toBeVisible();await page.goto('/admin/relatorios');await expect(page.getByText('Gastos do caixa')).toBeVisible();await expect(page.getByText('R$ 25,00')).toBeVisible()});

test('equipe ajusta carimbos de cartão físico com sessão protegida',async({page})=>{await loginAdmin(page);await page.goto('/admin/carimbos');await expect(page.getByRole('heading',{name:'Ajustar Carimbos'})).toBeVisible();await page.getByLabel('WhatsApp do cliente').fill('85999990000');await page.getByLabel('Quantidade atual da cartela física').fill('7');await page.getByLabel('Motivo').fill('Migração do cartão físico apresentado');await page.getByRole('button',{name:'Salvar ajuste de carimbos'}).click();await expect(page.getByText('Cliente Beta: cartão ficou com 7 de 14 carimbos.')).toBeVisible()});

test('reserva antecipada registra dia, calda e aviso de produção',async({page})=>{await page.goto('/cliente/reserva');await expect(page.locator('.flavor-preview-list').getByText('Trufado de ninho com morangos',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Confirmar reserva'}).click();await expect(page.getByRole('heading',{name:'Reserva criada!'})).toBeVisible();await expect(page.getByText('Pagamento antecipado')).toBeVisible();await expect(page.getByText('Se houver problema de produção')).toBeVisible()});

test('ações de reserva copiam link e abrem painel administrativo',async({page,context})=>{await context.grantPermissions(['clipboard-read','clipboard-write']);await page.goto('/cliente/reserva');await page.getByRole('button',{name:'Confirmar reserva'}).click();await page.getByRole('button',{name:'Copiar link de pagamento'}).click();await expect(page.getByText('Link de pagamento copiado.')).toBeVisible();await expect(await page.evaluate(()=>navigator.clipboard.readText())).toBe('https://mpago.la/reserva-demo');await loginAdmin(page);await page.goto('/admin/reservas');await expect(page.getByText('Cliente Beta · 1 fatia(s)')).toBeVisible();await page.getByRole('button',{name:'Pago'}).click();await expect(page.getByText(/pagamento antecipado · paid/)).toBeVisible();await page.getByRole('button',{name:'Separar'}).click();await expect(page.getByText(/pagamento antecipado · separating/)).toBeVisible();await page.getByRole('button',{name:'Aguardar retirada'}).click();await expect(page.getByText(/pagamento antecipado · waiting_pickup/)).toBeVisible();await page.getByRole('button',{name:'Finalizar retirada'}).click();await expect(page.getByText('picked_up')).toBeVisible()});

test('campanhas, tema sazonal e planejamento podem ser atualizados',async({page})=>{await loginAdmin(page);await page.goto('/admin/campanhas');await expect(page.getByRole('heading',{name:'Cards Promocionais'})).toBeVisible();await page.getByRole('button',{name:/Criar promoção relâmpago/}).click();await page.getByLabel('Título').first().fill('Promo relâmpago beta');await page.getByRole('button',{name:'Salvar card'}).first().click();await expect(page.getByText('Card salvo.')).toBeVisible();await page.getByLabel('Estilo sazonal').selectOption('brasil');await page.getByLabel('Ativar decoração sazonal no app do cliente').check();await page.getByLabel('Mensagem').fill('Garanta sua fatia antes do jogo');await page.getByRole('button',{name:'Salvar tema sazonal'}).click();await page.goto('/cliente');await expect(page.getByText('Garanta sua fatia antes do jogo')).toBeVisible();await page.goto('/admin/planejamento');await expect(page.getByRole('heading',{name:'Planejamento da Produção'})).toBeVisible();await page.getByRole('button',{name:'Adicionar sabor'}).first().click();await page.getByRole('button',{name:'Salvar planejamento'}).first().click();await expect(page.getByText('Planejamento salvo.')).toBeVisible()});

test('família, indicação convertida, perfil, prêmios e selos',async({page})=>{await page.goto('/cliente/familia');await expect(page.locator('.center-copy')).toContainText('Todos os membros compartilham os carimbos');await page.getByRole('button',{name:'Simular primeira compra paga'}).click();await expect(page.getByText('Indicação convertida e bônus liberado.')).toBeVisible();await page.goto('/cliente/perfil');await page.getByLabel('WhatsApp').fill('85999990000');await page.getByRole('button',{name:'Salvar perfil'}).click();await page.reload();await expect(page.getByLabel('WhatsApp')).toHaveValue('85999990000');await page.goto('/cliente/premios');await expect(page.getByText('Família Doce')).toBeVisible()});

test('maps, waze e uber usam busca pelo nome do festival',async({page})=>{await page.goto('/cliente/como-chegar');await expect(page.getByText('Festival de fatias Adoce Brigaderia').first()).toBeVisible();await expect(page.getByRole('link',{name:'Abrir no Waze'})).toHaveAttribute('href',/Festival%20de%20fatias%20Adoce%20Brigaderia/);await expect(page.getByRole('link',{name:'Abrir no Google Maps'})).toHaveAttribute('href',/Festival%20de%20fatias%20Adoce%20Brigaderia/);await expect(page.getByRole('link',{name:'Chamar Uber'})).toHaveAttribute('href',/uber/)});

test('atalhos e menus secundários navegam para o lugar certo',async({page})=>{await page.goto('/cliente');await page.getByRole('button',{name:'Perfil'}).click();await expect(page.getByRole('heading',{name:'Meu Perfil'})).toBeVisible();await page.goto('/cliente/mais');await page.getByRole('link',{name:/Sair/}).click();await expect(page.getByText('Acesse seu cartão fidelidade')).toBeVisible();await loginAdmin(page);await page.goto('/admin');await page.getByRole('link',{name:/Registrar Gasto/}).click();await expect(page).toHaveURL(/#gastos$/);await expect(page.getByRole('heading',{name:'Registrar gasto'})).toBeVisible();await page.goto('/admin/mais');await page.getByRole('link',{name:/Usuários/}).click();await expect(page).toHaveURL(/tab=usuarios/);await expect(page.getByRole('heading',{name:'Usuários Internos'})).toBeVisible();await page.getByRole('button',{name:'Sair'}).click();await expect(page.getByText('Acesso exclusivo da equipe')).toBeVisible()});

test('gestor navega e documentação volta ao painel',async({page})=>{await loginAdmin(page);for(const [label,url] of [['Vendas','/admin/vendas'],['Caixa','/admin/caixa'],['Relatórios','/admin/relatorios'],['Mais','/admin/mais']]){await page.getByRole('navigation').getByRole('link',{name:label,exact:true}).click();await expect(page).toHaveURL(new RegExp(url));await page.goto('/admin')}await page.goto('/admin/documentacao');await expect(page.getByRole('link',{name:'Voltar ao painel'})).toBeVisible()});

test('pagamento recusado e cobrança cancelada encerram a venda sem QR',async({page})=>{await openCash(page);await page.goto('/admin/vendas');await choosePayment(page,'Mercado Pago Point');await page.getByRole('button',{name:/Cliente Presencial/}).click();await page.getByRole('button',{name:'Pagamento recusado'}).click();await expect(page.getByRole('heading',{name:'Pagamento recusado'})).toBeVisible();await expect(page.getByText('Esta venda não gerou QR nem carimbo.')).toBeVisible();await expect(page.locator('.qr-frame')).toHaveCount(0);await page.getByRole('button',{name:'Nova venda'}).click();await choosePayment(page,'Mercado Pago Link');await page.getByRole('button',{name:/Delivery/}).click();await page.getByRole('button',{name:'Cancelar cobrança'}).click();await expect(page.getByRole('heading',{name:'Cobrança cancelada'})).toBeVisible();await expect(page.locator('.qr-frame')).toHaveCount(0)});

test('portal offline abre, busca e menu mobile funcionam',async({page})=>{await page.setViewportSize({width:390,height:844});await page.goto('file:///D:/Projetos/AdoceClub/Documentacao/Portal/index.html');await expect(page.getByRole('heading',{name:'Adoce Club',exact:true})).toBeVisible();const menu=page.getByRole('button',{name:'Abrir menu'});await menu.click();await expect(menu).toHaveAttribute('aria-expanded','true');await page.getByPlaceholder('Ex.: fidelidade, caixa, testes').fill('Mercado Pago');await expect(page.getByRole('heading',{name:'MVP Final Adoce Club'})).toBeVisible()});
