import { expect, test, type Page } from '@playwright/test';

async function reset(page:Page){await page.goto('/login');await page.evaluate(()=>localStorage.clear());await page.reload()}
async function loginAdmin(page:Page){await page.goto('/login');await page.getByRole('button',{name:'Entrar como Rubens / Gestor'}).click()}
async function openCash(page:Page){await loginAdmin(page);await page.goto('/admin/caixa');await page.getByRole('button',{name:'Abrir caixa agora'}).click()}
async function choosePayment(page:Page,name:string){await page.getByRole('button',{name,exact:true}).click()}

test.beforeEach(async({page})=>reset(page));

test('cliente home, navegação e logo sem borda preta',async({page})=>{await page.getByRole('button',{name:'Entrar como Cliente'}).click();await expect(page.getByText('Hoje é dia de fatia!')).toBeVisible();await expect(page.locator('.stamp-slot')).toHaveCount(14);await expect(page.locator('.brand-logo-frame')).toBeVisible();await expect(page.getByRole('link',{name:'Reservar agora'})).toBeVisible();await page.getByRole('link',{name:'Mais'}).click();await expect(page.getByText('Meu Perfil')).toBeVisible()});

test('botões principais cabem no viewport mobile',async({page})=>{await page.goto('/cliente');const overflow=await page.locator('body').evaluate(el=>el.scrollWidth>el.clientWidth);expect(overflow).toBeFalsy();for(const button of await page.locator('.primary-button').all()){const box=await button.evaluate(el=>({scroll:el.scrollWidth,client:el.clientWidth,height:(el as HTMLElement).offsetHeight}));expect(box.scroll).toBeLessThanOrEqual(box.client+1);expect(box.height).toBeGreaterThanOrEqual(48)}});

test('configurações gerais, empresa e taxas persistem',async({page})=>{await loginAdmin(page);await page.goto('/admin/configuracoes');await page.getByLabel('Preço da fatia').fill('18');await page.getByLabel('Carimbos para prêmio').fill('12');await page.getByLabel('Instagram').fill('@adoceoficial');await page.getByLabel('WhatsApp').fill('85988887777');await page.getByRole('button',{name:'Salvar configurações'}).click();await page.reload();await expect(page.getByLabel('Preço da fatia')).toHaveValue('18');await expect(page.getByLabel('Carimbos para prêmio')).toHaveValue('12');await page.getByRole('button',{name:'empresa'}).click();await page.getByLabel('tradeName').fill('Adoce Festival');await page.getByRole('button',{name:'Salvar dados da empresa'}).click();await page.reload();await page.getByRole('button',{name:'empresa'}).click();await expect(page.getByLabel('tradeName')).toHaveValue('Adoce Festival')});

for(const method of ['Dinheiro','Pix','Cartão'])test(`${method} gera QR e venda paga`,async({page})=>{await openCash(page);await page.goto('/admin/vendas');await choosePayment(page,method);await page.getByRole('button',{name:/Cliente Presencial/}).click();await expect(page.getByRole('heading',{name:'Venda registrada!'})).toBeVisible();await expect(page.locator('.qr-frame svg')).toBeVisible()});

for(const method of ['Cortesia','Permuta','Fidelidade'])test(`${method} registra saída sem QR`,async({page})=>{await openCash(page);await page.goto('/admin/vendas');await choosePayment(page,method);await page.getByLabel('Observação').fill('Operação demonstrativa');await page.getByRole('button',{name:/Cliente Presencial/}).click();await expect(page.getByRole('heading',{name:'Saída registrada!'})).toBeVisible();await expect(page.getByText('Esta operação não gera QR nem carimbo.')).toBeVisible();await expect(page.locator('.qr-frame')).toHaveCount(0)});

test('Mercado Pago Point usa terminal do login e só gera QR aprovado',async({page})=>{await openCash(page);await page.goto('/admin/vendas');await expect(page.getByText('Terminal:')).toContainText('Maquininha Rubens');await choosePayment(page,'Mercado Pago Point');await page.getByRole('button',{name:/Cliente Presencial/}).click();await expect(page.getByRole('heading',{name:'Aguardando pagamento'})).toBeVisible();await expect(page.locator('.qr-frame')).toHaveCount(0);await page.getByRole('button',{name:'Pagamento aprovado'}).click();await expect(page.getByRole('heading',{name:'Venda registrada!'})).toBeVisible()});

test('login Beth carrega terminal Beth',async({page})=>{await page.getByRole('button',{name:'Entrar como Beth'}).click();await page.goto('/admin/caixa');await page.getByRole('button',{name:'Abrir caixa agora'}).click();await page.goto('/vendedor/nova-venda');await expect(page.getByText('Terminal:')).toContainText('Maquininha Beth')});

test('Mercado Pago Link pendente não gera carimbo e pago libera QR',async({page})=>{await openCash(page);await page.goto('/admin/vendas');await choosePayment(page,'Mercado Pago Link');await page.getByRole('button',{name:/Delivery/}).click();await expect(page.getByText('Enquanto pendente, não gera QR nem carimbo.')).toBeVisible();await expect(page.locator('.qr-frame')).toHaveCount(0);await page.getByRole('button',{name:'Pagamento aprovado'}).click();await expect(page.getByRole('heading',{name:'Venda registrada!'})).toBeVisible()});

test('gasto aparece no relatório e fechamento',async({page})=>{await openCash(page);await page.getByLabel('Valor').fill('25');await page.getByLabel('Descrição').fill('Lanche da equipe');await page.getByRole('button',{name:'Salvar gasto'}).click();await expect(page.getByText('Gasto registrado.')).toBeVisible();await page.goto('/admin/relatorios');await expect(page.getByText('Gastos do caixa')).toBeVisible();await expect(page.getByText('R$ 25,00')).toBeVisible()});

test('reserva pendente não gera venda nem carimbo',async({page})=>{await page.goto('/cliente/reserva');await page.getByRole('button',{name:'Confirmar reserva'}).click();await expect(page.getByRole('heading',{name:'Reserva criada!'})).toBeVisible();await expect(page.getByText('Reserva pendente não baixa estoque e não gera carimbo.')).toBeVisible()});

test('família, indicação convertida, perfil, prêmios e selos',async({page})=>{await page.goto('/cliente/familia');await expect(page.locator('.center-copy')).toContainText('Todos os membros compartilham os carimbos');await page.getByRole('button',{name:'Simular primeira compra paga'}).click();await expect(page.getByText('Indicação convertida e bônus liberado.')).toBeVisible();await page.goto('/cliente/perfil');await page.getByLabel('WhatsApp').fill('85999990000');await page.getByRole('button',{name:'Salvar perfil'}).click();await page.reload();await expect(page.getByLabel('WhatsApp')).toHaveValue('85999990000');await page.goto('/cliente/premios');await expect(page.getByText('Família Doce')).toBeVisible()});

test('maps e waze usam links configurados',async({page})=>{await page.goto('/cliente/como-chegar');await expect(page.getByRole('link',{name:'Abrir no Waze'})).toHaveAttribute('href',/waze/);await expect(page.getByRole('link',{name:'Abrir no Google Maps'})).toHaveAttribute('href',/google/)});

test('gestor navega e documentação volta ao painel',async({page})=>{await loginAdmin(page);for(const [label,url] of [['Vendas','/admin/vendas'],['Caixa','/admin/caixa'],['Relatórios','/admin/relatorios'],['Mais','/admin/mais']]){await page.getByRole('navigation').getByRole('link',{name:label,exact:true}).click();await expect(page).toHaveURL(new RegExp(url));await page.goto('/admin')}await page.goto('/admin/documentacao');await expect(page.getByRole('link',{name:'Voltar ao painel'})).toBeVisible()});

test('portal offline abre, busca e menu mobile funcionam',async({page})=>{await page.setViewportSize({width:390,height:844});await page.goto('file:///D:/Projetos/AdoceClub/Documentacao/Portal/index.html');await expect(page.getByRole('heading',{name:'Adoce Club',exact:true})).toBeVisible();const menu=page.getByRole('button',{name:'Abrir menu'});await menu.click();await expect(menu).toHaveAttribute('aria-expanded','true');await page.getByPlaceholder('Ex.: fidelidade, caixa, testes').fill('Mercado Pago');await expect(page.getByRole('heading',{name:'MVP Final Adoce Club'})).toBeVisible()});
