import path from 'node:path';
import { expect, test, type Page } from '@playwright/test';
test.setTimeout(120_000);
const out=path.resolve('Documentacao/prints');
const shot=(page:Page,name:string)=>page.screenshot({path:path.join(out,name),fullPage:true});
async function mockBetaApi(page:Page){
  await page.route('**/.netlify/functions/customer-register',async route=>{const body=route.request().postDataJSON();await route.fulfill({json:{token:'test-token',customer:{id:'c1',name:body.name,whatsapp:body.whatsapp,email:'',instagram:'',birth_date:'',accepts_promotions:true},card:{stamps:0,stamps_required:14},events:[]}})});
  await page.route('**/.netlify/functions/customer-update',async route=>{const body=route.request().postDataJSON();await route.fulfill({json:{customer:{id:'c1',name:body.name,whatsapp:body.whatsapp,email:'',instagram:'',birth_date:'',accepts_promotions:true},card:{stamps:0,stamps_required:14},events:[]}})});
  await page.route('**/.netlify/functions/staff-login',async route=>{const body=route.request().postDataJSON();await route.fulfill({json:{token:'staff-token',operatorId:body.userId}})});
  await page.route('**/.netlify/functions/sale-create',async route=>{await route.fulfill({json:{id:'sale-cloud',token:`ADOCE-TEST-${Date.now()}`}})});
  await page.route('**/.netlify/functions/loyalty-claim',async route=>{await route.fulfill({json:{customer:{id:'c1',name:'Cliente Beta',whatsapp:'85999990000',email:'',instagram:'',birth_date:'',accepts_promotions:true},card:{stamps:3,stamps_required:14},events:[]}})});
}
async function register(page:Page){await page.goto('/cadastro');await page.getByRole('textbox',{name:'Nome'}).fill('Cliente Beta');await page.getByRole('textbox',{name:'WhatsApp'}).fill('85999990000');await page.getByLabel('Crie sua senha').fill('1234');await page.getByRole('checkbox',{name:/Aceito participar/}).check();await page.getByRole('checkbox',{name:/versão beta/}).check();await page.getByRole('button',{name:'Criar meu Adoce Club'}).click()}
async function admin(page:Page){await page.goto('/equipe');await page.getByLabel('PIN temporário').fill('1706');await page.getByRole('button',{name:'Entrar na operação'}).click();await expect(page).toHaveURL(/\/admin$/);await page.goto('/admin/caixa');await page.getByRole('button',{name:/Abrir caixa agora|Atualizar caixa/}).click()}
test('gera 21 prints finais',async({page})=>{await mockBetaApi(page);await page.goto('/cadastro');await page.evaluate(()=>localStorage.clear());await page.setViewportSize({width:390,height:844});await register(page);
await page.goto('/cliente');await shot(page,'01-cliente-home.png');await page.goto('/cliente/cartao');await shot(page,'02-cliente-cartao.png');await page.goto('/cliente/reserva');await shot(page,'03-cliente-reserva.png');await page.goto('/cliente/como-chegar');await shot(page,'04-cliente-como-chegar.png');await page.goto('/cliente/familia');await shot(page,'05-familia-indicacao.png');await page.goto('/cliente/premios');await shot(page,'06-fatia-premiada.png');
await admin(page);await page.goto('/admin');await shot(page,'07-gestor-painel.png');await page.goto('/admin/vendas');await shot(page,'08-gestor-vendas.png');await page.goto('/admin/caixa');await shot(page,'09-gestor-caixa.png');await shot(page,'10-registrar-gasto.png');await page.goto('/admin/vendas');await page.getByRole('button',{name:/Cliente Presencial/}).click();await shot(page,'11-venda-qr.png');await page.getByRole('button',{name:'Nova venda'}).click();await page.getByRole('button',{name:'Cortesia',exact:true}).click();await page.getByLabel('Observação').fill('Cortesia demonstrativa');await page.getByRole('button',{name:/Cliente Presencial/}).click();await shot(page,'12-saida-sem-qr.png');
await page.goto('/admin/vendas');await page.getByRole('button',{name:'Mercado Pago Point',exact:true}).click();await page.getByRole('button',{name:/Cliente Presencial/}).click();await shot(page,'13-mercado-pago-point-pendente.png');await page.getByRole('button',{name:'Pagamento aprovado'}).click();await shot(page,'14-mercado-pago-point-aprovada.png');await page.goto('/admin/vendas');await page.getByRole('button',{name:'Mercado Pago Link',exact:true}).click();await page.getByRole('button',{name:/Delivery/}).click();await shot(page,'15-delivery-link-pagamento.png');
await page.goto('/admin/configuracoes');await shot(page,'16-gestor-configuracoes-gerais.png');await page.getByRole('button',{name:'empresa'}).click();await shot(page,'17-gestor-configuracoes-empresa.png');await page.getByRole('button',{name:'mercado'}).click();await shot(page,'18-gestor-configuracoes-mercado-pago.png');await page.goto('/admin/relatorios');await shot(page,'19-gestor-relatorios.png');await page.goto('/documentacao/index.html');await page.setViewportSize({width:1280,height:850});await shot(page,'20-portal-documentacao.png');await page.setViewportSize({width:390,height:844});await shot(page,'21-portal-documentacao-mobile.png')});
