from pathlib import Path
p=Path('src/OperationManualSale.tsx')
s=p.read_text(encoding='utf-8')
s=s.replace('import OperationInstantOrders', 'import CashSessionActions from "./CashSessionActions";\nimport CashCustomerRegistration from "./CashCustomerRegistration";\nimport { validateDeferredSale } from "./cash-receivables";\nimport OperationInstantOrders')
s=s.replace('const [paymentModal,', 'const [deferred, setDeferred] = useState(false);\n  const [paymentModal,')
s=s.replace('if (mode === "sale" && totals.remaining > 0)', 'if (deferred && validateDeferredSale(name)) return setNotice(validateDeferredSale(name));\n    if (deferred && payments.length) return setNotice("Remova os pagamentos antes de deixar a venda totalmente pendente.");\n    if (mode === "sale" && !deferred && totals.remaining > 0)')
s=s.replace(': openCashSession\n        ?', ': deferred && openCashSession\n        ? await requireSupabase().rpc("staff_create_deferred_cash_sale", { target_session_id: openCashSession.id, target_draft_key: draftKey, requested_operation_key: operationKey, requested_customer_name: name, requested_items: items, requested_discount: discount, requested_notes: notes })\n        : openCashSession\n        ?')
s=s.replace('quantitiesRef.current = {}; setDraftKey', 'setDeferred(false); quantitiesRef.current = {}; setDraftKey')
s=s.replace('<div className="manual-sale-channel-switch', '<CashSessionActions sessionId={openCashSession?.id} storeId={openCashSession?.store_id || selectedStore?.id} hasDraft={items.length > 0} onChanged={() => void load()} />\n    <div className="manual-sale-channel-switch')
s=s.replace('<h3>Forma de pagamento</h3>', '<h3>Forma de pagamento</h3><label><input type="checkbox" checked={deferred} disabled={payments.length > 0} onChange={event => setDeferred(event.target.checked)} /> Pagamento pendente</label>{deferred ? <label>Nome e sobrenome do cliente<input autoComplete="name" value={name} onChange={event => setName(event.target.value)} required /><small>A venda será concluída e o estoque baixado. O valor ficará a receber.</small></label> : null}{notice ? <p role="alert">{notice}</p> : null}')
s=s.replace('className="cash-payment-methods"', 'className="cash-payment-methods" hidden={deferred}')
s=s.replace('hidden={method !== "pix"}', 'hidden={deferred || method !== "pix"}')
s=s.replace('<label>{method === "cash"', '<label hidden={deferred}>{method === "cash"')
s=s.replace('className="cash-add-payment"', 'className="cash-add-payment" hidden={deferred}')
s=s.replace('disabled={busy || reservationBusy || totals.remaining > 0}', 'disabled={busy || reservationBusy || (!deferred && totals.remaining > 0)}')
s=s.replace('{busy ? "Finalizando…" : totals.remaining > 0', '{busy ? "Finalizando…" : deferred ? "Finalizar com pagamento pendente" : totals.remaining > 0')
s=s.replace('<p>Deseja lançar carimbos', '<CashCustomerRegistration /><p>Deseja lançar carimbos')
p.write_text(s,encoding='utf-8')
