import { create } from 'zustand';
import { createJSONStorage, persist } from 'zustand/middleware';

export type Role = 'cliente' | 'vendedor' | 'admin';
export type Payment = 'Dinheiro' | 'Pix' | 'Cartão' | 'Mercado Pago Point' | 'Mercado Pago Link' | 'Cortesia' | 'Permuta' | 'Fidelidade';
export type SaleKind = 'Presencial' | 'Delivery / Retirada';
export type PaymentStatus = 'paid' | 'pending' | 'created' | 'sent_to_terminal' | 'waiting_payment' | 'declined' | 'cancelled' | 'expired';
export type ExpenseCategory = 'Custo c/ lanche' | 'Custo c/ insumos';
export type FlavorStock = { name:string; quantity:number; shortName?:string; imageUrl?:string };
export type DiscountType = 'none' | 'amount' | 'percent';
export type DiscountReason = 'Promoção' | 'Aniversário' | 'Cortesia parcial' | 'Ajuste manual' | 'Cupom/campanha';
export type ReservationStatus = 'requested' | 'waiting_payment' | 'paid' | 'confirmed' | 'separating' | 'waiting_pickup' | 'picked_up' | 'cancelled' | 'credit' | 'refunded' | 'expired';
export type PromoDay = 'quinta' | 'sexta' | 'sabado';
export type PromoCard = { id:string; day:PromoDay|'relampago'; title:string; date:string; validUntil:string; imageUrl:string; active:boolean; flash:boolean; flavors:FlavorStock[]; syrups:string[]; notes?:string };
export type PlannedProduction = { id:string; day:PromoDay; date:string; openingHour:string; flavors:FlavorStock[]; syrups:string[]; notes:string };
export type SeasonalTheme = { kind:'padrao'|'brasil'|'sao-joao'|'namorados'; active:boolean; startsAt:string; endsAt:string; message:string };
export type Product = { id:string; name:string; shortName:string; active:boolean; imageUrl?:string; createdAt:string; updatedAt:string };

export type CashExpense = { id:string; amount:number; category:ExpenseCategory; description:string; createdBy:string; createdAt:string };
export type ReservationItem = { flavor:string; quantity:number; syrup?:string };
export type SaleItem = ReservationItem;
export type Sale = { id:string; qty:number; items?:SaleItem[]; payment:Payment; kind:SaleKind; seller:string; operatorId:string; terminal?:string; terminalId?:string; flavor?:string; syrup?:string; token:string; claimed:boolean; createdAt:string; generatesQr:boolean; generatesStamps:boolean; subtotalAmount:number; discountType:DiscountType; discountValue:number; discountReason?:DiscountReason; discountNote?:string; discountAmount:number; grossAmount:number; feePercent:number; feeAmount:number; netAmount:number; status:PaymentStatus; notes?:string; paymentLinkUrl?:string };
export type Reservation = { id:string; customer:string; quantity:number; flavor:string; date:string; syrup?:string; items?:ReservationItem[]; deliveryType:SaleKind; status:ReservationStatus; paymentMethod:Payment; payNow:boolean; paymentLinkUrl?:string; createdAt:string; expiresAt:string; notes:string; cancelNote?:string };
export type Reward = { id:string; customer:string; type:string; origin:string; status:'pendente'|'retirado'|'expirado'|'cancelado'; generatedAt:string; redeemedAt?:string; confirmedBy?:string; notes?:string };
export type Badge = { id:string; name:string; earned:boolean; reason:string };
export type AuditLog = { id:string; action:string; createdAt:string; operator:string };
export type Family = { name:string; code:string; members:string[] };
export type Terminal = { id:string; name:string; nickname:string; operatorId:string; mercadoPagoTerminalId:string; storeId:string; posId:string; active:boolean; notes:string };
export type InternalUser = { id:string; name:string; login:string; role:'Sócio/Admin'|'Vendedor'; active:boolean; defaultTerminalId:string; canSwitchTerminal:boolean };
export type AppSettings = { price:number; cost:number; stampGoal:number; instagram:string; whatsapp:string; pixFee:number; cardFee:number; pointFee:number; linkPixFee:number; linkCardFee:number; referralBonusStamps:number; rewardValidityDays:number; birthdayDiscountEnabled:boolean; birthdayDiscountCapPercent:number; familyCardEnabled:boolean; luckySliceEnabled:boolean; defaultReward:string };
export type CompanySettings = { legalName:string; tradeName:string; cnpj:string; stateRegistration:string; whatsapp:string; instagram:string; email:string; address:string; neighborhood:string; city:string; state:string; zipCode:string; reference:string; placeName:string; latitude:string; longitude:string; mapsUrl:string; wazeUrl:string; uberUrl:string; openingHours:string; dailyCallout:string };
export type CustomerProfile = { name:string; whatsapp:string; email:string; instagram:string; birthDate:string; password:string; registered:boolean; lgpdAccepted:boolean; betaAccepted:boolean; acceptsPromotions:boolean; inviteCode?:string };

type State = {
  role:Role; currentUserId:string; staffAuthenticated:boolean; stamps:number; cashOpen:boolean; cashFund:number; available:number; producedPies:number; cashFlavors:FlavorStock[]; syrups:string[];
  settings:AppSettings; company:CompanySettings; customer:CustomerProfile; sales:Sale[]; expenses:CashExpense[]; reservations:Reservation[]; promoCards:PromoCard[]; plannedProductions:PlannedProduction[]; productCatalog:Product[]; seasonalTheme:SeasonalTheme; rewards:Reward[]; badges:Badge[]; audit:AuditLog[]; family:Family|null; referralCode:string; referrals:{customer:string;invited:number;converted:number;bonus:number}[]; terminals:Terminal[]; users:InternalUser[];
  setRole:(role:Role,userId?:string)=>void; loginStaff:(userId:string)=>void; logoutStaff:()=>void; registerCustomer:(customer:CustomerProfile)=>void; syncCustomer:(data:{customer:CustomerProfile;stamps:number;stampGoal?:number;rewards?:Reward[]})=>void; loginCustomer:(whatsapp:string,password:string)=>boolean; logoutCustomer:()=>void; openCash:(fund:number,available:number,producedPies?:number,flavors?:FlavorStock[],syrups?:string[])=>void; closeCash:()=>void;
  addSale:(data:{qty:number;items?:SaleItem[];payment:Payment;kind:SaleKind;notes?:string;flavor?:string;syrup?:string;discountType?:DiscountType;discountValue?:number;discountReason?:DiscountReason;discountNote?:string})=>Sale; replaceSaleToken:(id:string,token:string)=>void; updatePayment:(id:string,status:PaymentStatus)=>Sale|undefined; claim:(token:string)=>boolean;
  addExpense:(data:{amount:number;category:ExpenseCategory;description:string})=>void; addReservation:(data:Omit<Reservation,'id'|'createdAt'|'expiresAt'>)=>Reservation; updateReservation:(id:string,status:ReservationStatus,note?:string)=>void;
  savePromoCard:(card:PromoCard)=>void; savePlannedProduction:(plan:PlannedProduction)=>void; saveProduct:(product:Product)=>void; syncProductsFromCards:()=>void; saveTheme:(theme:SeasonalTheme)=>void;
  redeemReward:(id:string)=>void; createFamily:()=>void; joinFamily:(code:string)=>boolean; convertReferral:()=>void;
  saveSettings:(settings:Partial<AppSettings>)=>void; saveCompany:(company:Partial<CompanySettings>)=>void; saveCustomer:(customer:Partial<CustomerProfile>)=>void; saveTerminal:(terminal:Terminal)=>void; saveUser:(user:InternalUser)=>void;
};

export const paidPayments:Payment[]=['Dinheiro','Pix','Cartão','Mercado Pago Point','Mercado Pago Link'];
export const noQrPayments:Payment[]=['Cortesia','Permuta','Fidelidade'];
export const allPayments:Payment[]=[...paidPayments,...noQrPayments];
const now=()=>new Date().toLocaleString('pt-BR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'});
const uid=(prefix:string)=>`${prefix}${Date.now().toString(36).toUpperCase()}${Math.floor(Math.random()*99)}`;

const defaultSettings:AppSettings={price:16,cost:6.67,stampGoal:14,instagram:'@adocebrigaderia',whatsapp:'(85) 99999-9999',pixFee:.99,cardFee:3.49,pointFee:3.49,linkPixFee:.99,linkCardFee:4.99,referralBonusStamps:1,rewardValidityDays:30,birthdayDiscountEnabled:true,birthdayDiscountCapPercent:20,familyCardEnabled:true,luckySliceEnabled:true,defaultReward:'1 fatia grátis'};
const defaultCompany:CompanySettings={legalName:'',tradeName:'Adoce Brigaderia',cnpj:'',stateRegistration:'',whatsapp:'(85) 99999-9999',instagram:'@adocebrigaderia',email:'',address:'Festival de fatias Adoce Brigaderia',neighborhood:'',city:'',state:'CE',zipCode:'',reference:'',placeName:'Festival de fatias Adoce Brigaderia',latitude:'',longitude:'',mapsUrl:'https://www.google.com/maps/search/?api=1&query=Festival%20de%20fatias%20Adoce%20Brigaderia',wazeUrl:'https://waze.com/ul?q=Festival%20de%20fatias%20Adoce%20Brigaderia&navigate=yes',uberUrl:'',openingHours:'Quinta, sexta e sábado, 19h às 23h',dailyCallout:'Hoje é dia de fatia!'};
const defaultFlavors:FlavorStock[]=[{name:'Ninho com Morango',quantity:24},{name:'Brigadeiro Clássico',quantity:18},{name:'Chocolate Belga',quantity:18},{name:'Doce de Leite',quantity:12}];
const defaultSyrups=['Ninho','Brigadeiro'];
const quintaFlavors:FlavorStock[]=[{name:'Chocolatudo',quantity:6},{name:'Trufado de ninho com morangos',quantity:6},{name:'Ferrero Rocher',quantity:6},{name:'Redvelvet com geleia de morango e ninho',quantity:6},{name:'Mousse de limão',quantity:6},{name:'Ninho com Nutella',quantity:6}];
const sextaFlavors:FlavorStock[]=[{name:'Chocolatudo',quantity:6},{name:'Ferrero Rocher',quantity:6},{name:'Redvelvet com ninho e geleia de morango',quantity:6},{name:'Crocante de castanha e chocolate',quantity:6},{name:'Prestígio',quantity:6},{name:'Maracujá com chocolate',quantity:6},{name:'Abacaxi com coco',quantity:6},{name:'Surpresa de uva',quantity:6}];
const sabadoFlavors:FlavorStock[]=[{name:'Chocolatudo',quantity:6},{name:'Trufado de ninho com morangos na massa cacau black',quantity:6},{name:'Ferrero Rocher',quantity:6},{name:'Redvelvet Ninho com Nutella',quantity:6},{name:'Oreo',quantity:6},{name:'Olho de sogra',quantity:6},{name:'Limão siciliano com frutas vermelhas',quantity:6},{name:'Crocante com churros',quantity:6}];
const defaultPromoCards:PromoCard[]=[
  {id:'promo-quinta',day:'quinta',title:'Quinta-feira, 18/06',date:'2026-06-18',validUntil:'2026-06-18T23:59:59-03:00',imageUrl:'/assets/promos/quinta.jpeg',active:true,flash:false,flavors:quintaFlavors,syrups:defaultSyrups,notes:'Card de sabores da quinta.'},
  {id:'promo-sexta',day:'sexta',title:'Sexta-feira, 19/06',date:'2026-06-19',validUntil:'2026-06-19T23:59:59-03:00',imageUrl:'/assets/promos/sexta.jpeg',active:true,flash:false,flavors:sextaFlavors,syrups:defaultSyrups,notes:'Card de sabores da sexta.'},
  {id:'promo-sabado',day:'sabado',title:'Sábado, 20/06',date:'2026-06-20',validUntil:'2026-06-20T23:59:59-03:00',imageUrl:'/assets/promos/sabado.jpeg',active:true,flash:false,flavors:sabadoFlavors,syrups:defaultSyrups,notes:'Card de sabores do sábado.'},
];
const defaultPlans:PlannedProduction[]=defaultPromoCards.filter(c=>c.day!=='relampago').map(c=>({id:`plan-${c.day}`,day:c.day as PromoDay,date:c.date,openingHour:c.day==='sabado'?'18:00':'19:00',flavors:c.flavors,syrups:c.syrups,notes:'Planejamento inicial importado dos cards da semana.'}));
const defaultTheme:SeasonalTheme={kind:'padrao',active:false,startsAt:'',endsAt:'',message:''};
const terminals:Terminal[]=[{id:'term-rubens',name:'Maquininha Rubens',nickname:'Point Rubens',operatorId:'rubens',mercadoPagoTerminalId:'MOCK-RUBENS',storeId:'STORE-DEMO',posId:'POS-RUBENS',active:true,notes:'Terminal demonstrativo'},{id:'term-beth',name:'Maquininha Beth',nickname:'Point Beth',operatorId:'beth',mercadoPagoTerminalId:'MOCK-BETH',storeId:'STORE-DEMO',posId:'POS-BETH',active:true,notes:'Terminal demonstrativo'}];
const users:InternalUser[]=[{id:'rubens',name:'Rubens',login:'rubens',role:'Sócio/Admin',active:true,defaultTerminalId:'term-rubens',canSwitchTerminal:true},{id:'beth',name:'Beth',login:'beth',role:'Vendedor',active:true,defaultTerminalId:'term-beth',canSwitchTerminal:false}];
const feeFor=(p:Payment,s:AppSettings)=>p==='Pix'?s.pixFee:p==='Cartão'?s.cardFee:p==='Mercado Pago Point'?s.pointFee:p==='Mercado Pago Link'?s.linkCardFee:0;
const discountFor=(subtotal:number,type:DiscountType='none',value=0)=>Math.min(subtotal,Math.max(0,type==='percent'?subtotal*(value/100):type==='amount'?value:0));
const productKey=(name:string)=>name.trim().normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\s+/g,' ');
const shortNameFor=(name:string)=>{const clean=name.trim();const words=clean.split(/\s+/).filter(Boolean);return (words[0]||clean||'Fatia').slice(0,14);};
const productsFromFlavors=(flavors:FlavorStock[])=>[...new Map(flavors.map(f=>[productKey(f.name),f])).values()].filter(f=>f.name.trim()).map(f=>({id:uid('PROD'),name:f.name,shortName:f.shortName||shortNameFor(f.name),active:true,imageUrl:f.imageUrl,createdAt:now(),updatedAt:now()}));
const defaultProducts=productsFromFlavors([...defaultFlavors,...quintaFlavors,...sextaFlavors,...sabadoFlavors]);

export const useStore=create<State>()(persist((set,get)=>({
  role:'cliente',currentUserId:'rubens',staffAuthenticated:false,stamps:0,cashOpen:false,cashFund:0,available:72,producedPies:6,cashFlavors:defaultFlavors,syrups:defaultSyrups,settings:defaultSettings,company:defaultCompany,customer:{name:'',whatsapp:'',email:'',instagram:'',birthDate:'',password:'',registered:false,lgpdAccepted:false,betaAccepted:false,acceptsPromotions:true,inviteCode:''},sales:[],expenses:[],reservations:[],promoCards:defaultPromoCards,plannedProductions:defaultPlans,productCatalog:defaultProducts,seasonalTheme:defaultTheme,rewards:[],badges:[{id:'top',name:'Cliente Top',earned:false,reason:'Complete sua primeira cartela'},{id:'first',name:'Primeira Cartela Completa',earned:false,reason:'Complete 14 carimbos'},{id:'family',name:'Família Doce',earned:false,reason:'Participe de um cartão familiar'},{id:'referral',name:'Indicador Doce',earned:false,reason:'Converta 3 indicações'},{id:'delivery',name:'Cliente Delivery',earned:false,reason:'Compre por delivery'},{id:'vip',name:'Cliente VIP',earned:false,reason:'Benefício futuro'}],audit:[],family:null,referralCode:'BEZERRA10',referrals:[{customer:'Cliente Demo',invited:4,converted:2,bonus:2},{customer:'Maria Júlia',invited:3,converted:1,bonus:1}],terminals,users,
  setRole:(role,userId)=>set({role,currentUserId:userId??(role==='vendedor'?'beth':'rubens')}),
  loginStaff:userId=>set({role:userId==='beth'?'vendedor':'admin',currentUserId:userId,staffAuthenticated:true}),
  logoutStaff:()=>set({staffAuthenticated:false,role:'cliente'}),
  registerCustomer:customer=>set({role:'cliente',customer:{...customer,registered:true}}),
  syncCustomer:data=>set(s=>({role:'cliente',customer:{...data.customer,registered:true,password:''},stamps:data.stamps,rewards:data.rewards??s.rewards,settings:{...s.settings,stampGoal:data.stampGoal??s.settings.stampGoal}})),
  loginCustomer:(whatsapp,password)=>{const c=get().customer;const ok=c.registered&&c.whatsapp.replace(/\D/g,'')===whatsapp.replace(/\D/g,'')&&c.password===password;if(ok)set({role:'cliente'});return ok;},
  logoutCustomer:()=>set({role:'cliente'}),
  openCash:(cashFund,available,producedPies=6,flavors,syrups)=>set(s=>{const catalog=s.productCatalog??[];const cleanFlavors=(flavors?.filter(f=>f.name.trim()&&f.quantity>0)??s.cashFlavors);const cleanSyrups=(syrups?.map(v=>v.trim()).filter(Boolean)??s.syrups);const total=cleanFlavors.reduce((a,v)=>a+v.quantity,0)||available;const catalogByName=new Map(catalog.map(p=>[productKey(p.name),p]));const nextCatalog=[...catalog];for(const flavor of cleanFlavors){const key=productKey(flavor.name);if(!catalogByName.has(key)){const product={id:uid('PROD'),name:flavor.name,shortName:flavor.shortName||shortNameFor(flavor.name),active:true,imageUrl:flavor.imageUrl,createdAt:now(),updatedAt:now()};nextCatalog.push(product);catalogByName.set(key,product);}}return{cashOpen:true,cashFund,available:total,producedPies,cashFlavors:cleanFlavors,syrups:cleanSyrups,productCatalog:nextCatalog,audit:[{id:uid('AUD'),action:`${s.users.find(u=>u.id===s.currentUserId)?.name} abriu o caixa com ${total} fatias.`,createdAt:now(),operator:s.currentUserId},...s.audit]};}),
  closeCash:()=>set(s=>({cashOpen:false,audit:[{id:uid('AUD'),action:`${s.users.find(u=>u.id===s.currentUserId)?.name} fechou o caixa.`,createdAt:now(),operator:s.currentUserId},...s.audit]})),
  addSale:data=>{const s=get();const user=s.users.find(u=>u.id===s.currentUserId)??s.users[0];const terminal=s.terminals.find(t=>t.id===user.defaultTerminalId);const paidManual=['Dinheiro','Pix','Cartão'].includes(data.payment);const nonRevenue=noQrPayments.includes(data.payment);const status:PaymentStatus=paidManual||nonRevenue?'paid':data.payment==='Mercado Pago Point'?'waiting_payment':'pending';const items=(data.items?.length?data.items:[{flavor:data.flavor??'',quantity:data.qty,syrup:data.syrup}]).filter(i=>i.quantity>0);const qty=items.reduce((a,v)=>a+v.quantity,0)||data.qty;const flavorSummary=items.map(i=>i.flavor).filter(Boolean).join(' + ')||data.flavor;const syrupSummary=items.length===1?items[0].syrup:data.syrup;const subtotal=nonRevenue?0:qty*s.settings.price;const discountAmount=discountFor(subtotal,data.discountType,data.discountValue);const gross=+(subtotal-discountAmount).toFixed(2);const fee=feeFor(data.payment,s.settings);const sale:Sale={id:uid('V'),qty,items,payment:data.payment,kind:data.kind,seller:user.name,operatorId:user.id,terminal:terminal?.name,terminalId:terminal?.id,flavor:flavorSummary,syrup:syrupSummary,token:uid('ADOCE-'),claimed:false,createdAt:now(),generatesQr:paidManual,generatesStamps:paidManual,subtotalAmount:subtotal,discountType:data.discountType??'none',discountValue:data.discountValue??0,discountReason:data.discountReason,discountNote:data.discountNote,discountAmount, grossAmount:gross,feePercent:fee,feeAmount:+(gross*fee/100).toFixed(2),netAmount:+(gross-(gross*fee/100)).toFixed(2),status,notes:data.notes,paymentLinkUrl:data.payment==='Mercado Pago Link'?`https://mpago.la/mock-${uid('L')}`:undefined};set(st=>({sales:[sale,...st.sales],audit:[{id:uid('AUD'),action:`${user.name} registrou ${data.payment} de ${qty} fatias${flavorSummary?` (${flavorSummary})`:''}${discountAmount?` com desconto de R$ ${discountAmount.toFixed(2)}`:''}.`,createdAt:now(),operator:user.name},...st.audit]}));return sale;},
  replaceSaleToken:(id,token)=>set(s=>({sales:s.sales.map(v=>v.id===id?{...v,token}:v)})),
  updatePayment:(id,status)=>{let result:Sale|undefined;set(s=>({sales:s.sales.map(sale=>{if(sale.id!==id)return sale;const paid=status==='paid';result={...sale,status,generatesQr:paid,generatesStamps:paid};return result;}),audit:[{id:uid('AUD'),action:`Pagamento ${status} na venda ${id}.`,createdAt:now(),operator:s.currentUserId},...s.audit]}));return result;},
  claim:token=>{const s=get();const sale=s.sales.find(v=>v.token===token);if(!sale||sale.claimed||!sale.generatesStamps||sale.status!=='paid')return false;const total=s.stamps+sale.qty;const completed=Math.floor(total/s.settings.stampGoal);set(st=>({stamps:total%s.settings.stampGoal,sales:st.sales.map(v=>v.id===sale.id?{...v,claimed:true}:v),rewards:completed?[{id:uid('P'),customer:st.customer.name,type:st.settings.defaultReward,origin:'cartela completa',status:'pendente',generatedAt:now()},...st.rewards]:st.rewards,badges:completed?st.badges.map(b=>b.id==='top'||b.id==='first'?{...b,earned:true}:b):st.badges}));return true;},
  addExpense:data=>set(s=>({expenses:[{...data,id:uid('G'),createdBy:s.users.find(u=>u.id===s.currentUserId)?.name??'Operador',createdAt:now()},...s.expenses],audit:[{id:uid('AUD'),action:`Gasto de R$ ${data.amount.toFixed(2)} em ${data.category}.`,createdAt:now(),operator:s.currentUserId},...s.audit]})),
  addReservation:data=>{const reservation:Reservation={...data,id:uid('R'),createdAt:now(),expiresAt:`${data.date || 'Hoje'}, 20:00`};set(s=>({reservations:[reservation,...s.reservations]}));return reservation;},
  updateReservation:(id,status,note)=>set(s=>({reservations:s.reservations.map(r=>r.id===id?{...r,status,cancelNote:note??r.cancelNote}:r),audit:[{id:uid('AUD'),action:`Reserva ${id} alterada para ${status}${note?`: ${note}`:''}.`,createdAt:now(),operator:s.currentUserId},...s.audit]})),redeemReward:id=>set(s=>({rewards:s.rewards.map(r=>r.id===id?{...r,status:'retirado',redeemedAt:now(),confirmedBy:s.currentUserId}:r)})),
  savePromoCard:card=>set(s=>{const catalog=s.productCatalog??[];const existing=new Map(catalog.map(p=>[productKey(p.name),p]));const additions=card.flavors.filter(f=>f.name.trim()&&!existing.has(productKey(f.name))).map(f=>({id:uid('PROD'),name:f.name,shortName:f.shortName||shortNameFor(f.name),active:true,imageUrl:f.imageUrl,createdAt:now(),updatedAt:now()}));return{promoCards:s.promoCards.some(c=>c.id===card.id)?s.promoCards.map(c=>c.id===card.id?card:c):[card,...s.promoCards],productCatalog:[...catalog,...additions],audit:[{id:uid('AUD'),action:`Card promocional atualizado: ${card.title}.`,createdAt:now(),operator:s.currentUserId},...s.audit]};}),
  savePlannedProduction:plan=>set(s=>{const catalog=s.productCatalog??[];const existing=new Map(catalog.map(p=>[productKey(p.name),p]));const additions=plan.flavors.filter(f=>f.name.trim()&&!existing.has(productKey(f.name))).map(f=>({id:uid('PROD'),name:f.name,shortName:f.shortName||shortNameFor(f.name),active:true,imageUrl:f.imageUrl,createdAt:now(),updatedAt:now()}));return{plannedProductions:s.plannedProductions.some(p=>p.id===plan.id)?s.plannedProductions.map(p=>p.id===plan.id?plan:p):[plan,...s.plannedProductions],productCatalog:[...catalog,...additions],audit:[{id:uid('AUD'),action:`Planejamento atualizado para ${plan.date}.`,createdAt:now(),operator:s.currentUserId},...s.audit]};}),
  saveProduct:product=>set(s=>{const catalog=s.productCatalog??[];return{productCatalog:catalog.some(p=>p.id===product.id)?catalog.map(p=>p.id===product.id?{...product,updatedAt:now()}:p):[{...product,id:product.id||uid('PROD'),createdAt:now(),updatedAt:now()},...catalog],audit:[{id:uid('AUD'),action:`Produto atualizado: ${product.name}.`,createdAt:now(),operator:s.currentUserId},...s.audit]};}),
  syncProductsFromCards:()=>set(s=>{const catalog=s.productCatalog??[];const existing=new Map(catalog.map(p=>[productKey(p.name),p]));const allFlavors=[...s.promoCards.flatMap(c=>c.flavors),...s.plannedProductions.flatMap(p=>p.flavors),...s.cashFlavors];const additions=allFlavors.filter(f=>f.name.trim()&&!existing.has(productKey(f.name))).map(f=>{const p={id:uid('PROD'),name:f.name,shortName:f.shortName||shortNameFor(f.name),active:true,imageUrl:f.imageUrl,createdAt:now(),updatedAt:now()};existing.set(productKey(f.name),p);return p;});return{productCatalog:[...catalog,...additions],audit:[{id:uid('AUD'),action:`Catálogo sincronizado com ${additions.length} novo(s) sabor(es).`,createdAt:now(),operator:s.currentUserId},...s.audit]};}),
  saveTheme:theme=>set(s=>({seasonalTheme:theme,audit:[{id:uid('AUD'),action:`Tema sazonal alterado para ${theme.kind}.`,createdAt:now(),operator:s.currentUserId},...s.audit]})),
  createFamily:()=>set({family:{name:'Família Doce',code:'FAMILIA-DOCE',members:['Cliente Demo']}}),joinFamily:code=>{if(code.trim().toUpperCase()!=='FAMILIA-DOCE')return false;set({family:{name:'Família Doce',code:'FAMILIA-DOCE',members:['Cliente Demo','Novo membro']}});return true;},
  convertReferral:()=>set(s=>{const total=s.stamps+s.settings.referralBonusStamps;return{stamps:total%s.settings.stampGoal,referrals:s.referrals.map((r,i)=>i? r:{...r,converted:r.converted+1,bonus:r.bonus+s.settings.referralBonusStamps}),badges:s.badges.map(b=>b.id==='referral'&&s.referrals[0].converted+1>=3?{...b,earned:true}:b)};}),
  saveSettings:settings=>set(s=>({settings:{...s.settings,...settings},audit:[{id:uid('AUD'),action:'Configurações gerais alteradas.',createdAt:now(),operator:s.currentUserId},...s.audit]})),saveCompany:company=>set(s=>({company:{...s.company,...company}})),saveCustomer:customer=>set(s=>({customer:{...s.customer,...customer}})),saveTerminal:terminal=>set(s=>({terminals:s.terminals.some(t=>t.id===terminal.id)?s.terminals.map(t=>t.id===terminal.id?terminal:t):[...s.terminals,terminal]})),saveUser:user=>set(s=>({users:s.users.some(u=>u.id===user.id)?s.users.map(u=>u.id===user.id?user:u):[...s.users,user]})),
}),{name:'adoce-club-mvp-final',storage:createJSONStorage(()=>localStorage),version:5}));
